In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/adult.csv')

In [ ]:
data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
data.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
# their is no missing value

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data1=data.copy()

In [ ]:
data1

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
labelencoder=LabelEncoder()
categorical_cols_indices = [-1, 13, 9, 8, 7, 6, 5, 3, 1]
data1.iloc[:, categorical_cols_indices] = data1.iloc[:, categorical_cols_indices].apply(lambda col: LabelEncoder().fit_transform(col))

In [ ]:
data1

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,4,257302,7,12,2,13,5,4,0,0,0,38,39,0
32557,40,4,154374,11,9,2,7,0,4,1,0,0,40,39,1
32558,58,4,151910,11,9,6,1,4,4,0,0,0,40,39,0
32559,22,4,201490,11,9,4,1,3,4,1,0,0,20,39,0
32560,52,5,287927,11,9,2,4,5,4,0,15024,0,40,39,1

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
data2=data.copy()
data2

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
data2.reset_index(drop=True,inplace=True)
data2

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
OHE=OneHotEncoder()

In [ ]:
enc_df=pd.DataFrame(OHE.fit_transform(data2[['income']]).toarray())

In [ ]:
enc_df

         0    1
0      1.0  0.0
1      1.0  0.0
2      1.0  0.0
3      1.0  0.0
4      1.0  0.0
...    ...  ...
32556  1.0  0.0
32557  0.0  1.0
32558  1.0  0.0
32559  1.0  0.0
32560  0.0  1.0

[32561 rows x 2 columns]

In [ ]:
data_final=data2.iloc[:,0:14].join(enc_df)
data_final
#

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,0,1
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,1.0,0.0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,1.0,0.0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,1.0,0.0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,1.0,0.0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,1.0,0.0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,0.0,1.0
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,1.0,0.0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,1.0,0.0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,0.0,1.0

In [ ]:
# IsolationForest

In [ ]:
from sklearn.ensemble import IsolationForest

In [ ]:
iso=IsolationForest(random_state=10,contamination=0.1)
iso.fit(data1)
out=iso.predict(data1)

In [ ]:
out

array([ 1,  1,  1, ...,  1,  1, -1])

In [ ]:
# -1 is an outlier and 1 is a normal data point

In [ ]:
data1['score']=out
data1

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,score
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0,1
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0,1
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0,1
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0,1
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,4,257302,7,12,2,13,5,4,0,0,0,38,39,0,1
32557,40,4,154374,11,9,2,7,0,4,1,0,0,40,39,1,1
32558,58,4,151910,11,9,6,1,4,4,0,0,0,40,39,0,1
32559,22,4,201490,11,9,4,1,3,4,1,0,0,20,39,0,1
32560,52,5,287927,11,9,2,4,5,4,0,15024,0,40,39,1,-1

In [ ]:
data_encoded=pd.get_dummies(data)
data_encoded

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native_country_ Scotland,native_country_ South,native_country_ Taiwan,native_country_ Thailand,native_country_ Trinadad&Tobago,native_country_ United-States,native_country_ Vietnam,native_country_ Yugoslavia,income_ <=50K,income_ >50K
0,39,77516,13,2174,0,40,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
1,50,83311,13,0,0,13,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
2,38,215646,9,0,0,40,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
3,53,234721,7,0,0,40,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
4,28,338409,13,0,0,40,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,257302,12,0,0,38,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
32557,40,154374,9,0,0,40,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
32558,58,151910,9,0,0,40,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
32559,22,201490,9,0,0,20,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
32560,52,287927,9,15024,0,40,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True

In [ ]:
clf=IsolationForest(random_state=10,contamination=0.1)
clf.fit(data_encoded)
y_pred=clf.predict(data_encoded)

In [ ]:
y_pred

array([ 1,  1,  1, ...,  1,  1, -1])

In [ ]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:110])
# we can pinpoint those outliers exactly by applying these filtering score

In [ ]:
data_encoded

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native_country_ South,native_country_ Taiwan,native_country_ Thailand,native_country_ Trinadad&Tobago,native_country_ United-States,native_country_ Vietnam,native_country_ Yugoslavia,income_ <=50K,income_ >50K,anomaly
0,39,77516,13,2174,0,40,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
1,50,83311,13,0,0,13,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
2,38,215646,9,0,0,40,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
3,53,234721,7,0,0,40,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
4,28,338409,13,0,0,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,257302,12,0,0,38,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
32557,40,154374,9,0,0,40,False,False,False,False,...,False,False,False,False,True,False,False,False,True,1
32558,58,151910,9,0,0,40,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
32559,22,201490,9,0,0,20,False,False,False,False,...,False,False,False,False,True,False,False,True,False,1
32560,52,287927,9,15024,0,40,False,False,False,False,...,False,False,False,False,True,False,False,False,True,-1

In [ ]:
# Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native_country_ South,native_country_ Taiwan,native_country_ Thailand,native_country_ Trinadad&Tobago,native_country_ United-States,native_country_ Vietnam,native_country_ Yugoslavia,income_ <=50K,income_ >50K,anomaly
4,28,338409,13,0,0,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,-1
6,49,160187,5,0,0,16,False,False,False,False,...,False,False,False,False,False,False,False,True,False,-1
11,30,141297,13,0,0,40,False,False,False,False,...,False,False,False,False,False,False,False,False,True,-1
14,40,121772,11,0,0,40,False,False,False,False,...,False,False,False,False,False,False,False,False,True,-1
15,34,245487,4,0,0,45,False,False,False,False,...,False,False,False,False,False,False,False,True,False,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32544,31,199655,14,0,0,30,False,False,False,False,...,False,False,False,False,True,False,False,True,False,-1
32545,39,111499,12,0,0,20,False,False,True,False,...,False,False,False,False,True,False,False,False,True,-1
32551,32,34066,6,0,0,40,False,False,False,False,...,False,False,False,False,True,False,False,True,False,-1
32553,32,116138,14,0,0,11,False,False,False,False,...,False,True,False,False,False,False,False,True,False,-1
32560,52,287927,9,15024,0,40,False,False,False,False,...,False,False,False,False,True,False,False,False,True,-1

In [ ]:
data_encoded['anomaly'].value_counts()

anomaly
 1    29305
-1     3256
Name: count, dtype: int64

In [ ]:
!pip install --upgrade ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.12/dist-packages (1.3.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.7.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.17.0)

In [ ]:
! pip install ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.12/dist-packages (1.3.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.7.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.17.0)

In [ ]:
%pip install ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.12/dist-packages (1.3.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.7.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.17.0)

In [ ]:
!pip install git+https://github.com/8080labs/ppscore.git --no-cache-dir

Collecting git+https://github.com/8080labs/ppscore.git
  Cloning https://github.com/8080labs/ppscore.git to /tmp/pip-req-build-oswdna3_
  Running command git clone --filter=blob:none --quiet https://github.com/8080labs/ppscore.git /tmp/pip-req-build-oswdna3_
  Resolved https://github.com/8080labs/ppscore.git to commit 756dc2619ae4ac4d2e66635a730eff14a8101eb1
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ppscore==1.3.0) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.12/dist-packages (from ppscore==1.3.0) (1.7.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ppscore==1.3.0) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ppscore==1.3.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ppscore==1.3.0) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore==1.3.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore==1.3.0) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore==1.3.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->pandas>=1.0.0->ppscore==1.3.0) (1.17.0)

In [ ]:
import ppscore as ps

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [ ]:
'''
import sys

# Uninstall all potentially conflicting packages
!pip uninstall -y ppscore pandas numpy scipy scikit-learn

# Install a specific numpy version known to be compatible with pandas 1.x and scikit-learn < 2.0
# Note: numpy 1.24.4 is chosen as a stable version within the numpy 1.x series.
!pip install numpy==1.24.4

# Install a specific pandas version compatible with ppscore's requirement (<2.0.0)
# This needs to be installed AFTER numpy to ensure ABI compatibility.
!pip install pandas==1.5.3

# Now install ppscore, which should find compatible dependencies
!pip install ppscore

Found existing installation: ppscore 1.3.0
Uninstalling ppscore-1.3.0:
  Successfully uninstalled ppscore-1.3.0
Found existing installation: pandas 1.5.3
Uninstalling pandas-1.5.3:
  Successfully uninstalled pandas-1.5.3
Found existing installation: numpy 2.3.5
Uninstalling numpy-2.3.5:
  Successfully uninstalled numpy-2.3.5
Found existing installation: scipy 1.16.3
Uninstalling scipy-1.16.3:
  Successfully uninstalled scipy-1.16.3
Found existing installation: scikit-learn 1.7.2
Uninstalling scikit-learn-1.7.2:
  Successfully uninstalled scikit-learn-1.7.2
Collecting numpy==1.24.4
  Downloading numpy-1.24.4.tar.gz (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 61.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Collecting pandas==1.5.3
  Using cached pandas-1.5.3-cp312-cp312-linux_x86_64.whl
Collecting numpy>=1.21.0 (from pandas==1.5.3)
  Using cached numpy-2.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from pandas==1.5.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==1.5.3) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->pandas==1.5.3) (1.17.0)
Using cached numpy-2.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Installing collected packages: numpy, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cuml-cu12 25.10.0 requires scikit-learn>=1.4, which is not installed.
cuml-cu12 25.10.0 requires scipy>=1.8.0, which is not installed.
statsmodels 0.14.5 requires scipy!=1.9.2,>=1.8, which is not installed.
cvxpy 1.6.7 requires scipy>=1.11.0, which is not installed.
xgboost 3.1.1 requires scipy, which is not installed.
hdbscan 0.8.40 requires scikit-learn>=0.20, which is not installed.
hdbscan 0.8.40 requires scipy>=1.0, which is not installed.
imbalanced-learn 0.14.0 requires scikit-learn<2,>=1.4.2, which is not installed.
imbalanced-learn 0.14.0 requires scipy<2,>=1.11.4, which is not installed.
plotnine 0.14.5 requires scipy>=1.8.0, which is not installed.
hyperopt 0.2.7 requires scipy, which is not installed.
missingno 0.5.2 requires scipy, which is not installed.
arviz 0.22.0 requires scipy>=1.11.0, which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", which is not installed.
mizani 0.13.5 requires scipy>=1.8.0, which is not installed.
pymc 5.26.1 requires scipy>=1.4.1, which is not installed.
pytensor 2.35.1 requires scipy<2,>=1, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
yellowbrick 1.5 requires scipy>=1.0.0, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
mlxtend 0.23.4 requires scipy>=1.2.1, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
librosa 0.11.0 requires scipy>=1.6.0, which is not installed.
treelite 4.4.1 requires scipy, which is not installed.
libpysal 4.13.0 requires scikit-learn>=1.1, which is not installed.
libpysal 4.13.0 requires scipy>=1.8, which is not installed.
scikit-image 0.25.2 requires scipy>=1.11.4, which is not installed.
jaxlib 0.7.2 requires scipy>=1.13, which is not installed.
osqp 1.0.5 requires scipy>=0.13.2, which is not installed.
sentence-transformers 5.1.2 requires scikit-learn, which is not installed.
sentence-transformers 5.1.2 requires scipy, which is not installed.
jax 0.7.2 requires scipy>=1.13, which is not installed.
albumentations 2.0.8 requires scipy>=1.10.0, which is not installed.
lightgbm 4.6.0 requires scipy, which is not installed.
clarabel 0.11.1 requires scipy, which is not installed.
matplotlib-venn 1.1.2 requires scipy, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
sklearn-pandas 2.2.0 requires scipy>=1.5.1, which is not installed.
shap 0.50.0 requires scikit-learn, which is not installed.
shap 0.50.0 requires scipy, which is not installed.
scs 3.2.9 requires scipy, which is not installed.
fastai 2.8.5 requires scikit-learn, which is not installed.
fastai 2.8.5 requires scipy, which is not installed.
umap-learn 0.5.9.post2 requires scikit-learn>=1.6, which is not installed.
umap-learn 0.5.9.post2 requires scipy>=1.3.1, which is not installed.
stumpy 1.13.0 requires scipy>=1.10, which is not installed.
xarray-einstats 0.9.1 requires scipy>=1.11, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 1.5.3 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.5 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.5 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
cudf-cu12 25.10.0 requires pandas<2.4.0dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
geopandas 1.1.1 requires pandas>=2.0.0, but you have pandas 1.5.3 which is incompatible.
arviz 0.22.0 requires pandas>=2.1.0, but you have pandas 1.5.3 which is incompatible.
mizani 0.13.5 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.5 which is incompatible.
xarray 2025.10.1 requires pandas>=2.2, but you have pandas 1.5.3 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.5 which is incompatible.
dask-cudf-cu12 25.10.0 requires pandas<2.4.0dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.5 which is incompatible.
Successfully installed numpy-2.3.5 pandas-1.5.3

Collecting ppscore
  Using cached ppscore-1.3.0-py2.py3-none-any.whl
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ppscore) (1.5.3)
Collecting scikit-learn<2.0.0,>=0.20.2 (from ppscore)
  Using cached scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2025.2)
Collecting scipy>=1.8.0 (from scikit-learn<2.0.0,>=0.20.2->ppscore)
  Using cached scipy-1.16.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.17.0)
Using cached scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.5 MB)
Using cached scipy-1.16.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.7 MB)
^C

In [ ]:
'''
The pip command is not compatible with the new version, and the only alternative would be to change the kernel to an older version in order to run pip.
Therefore, i may skip that task and proceed to submit the assignment.